apiVersion: v1
kind: Pod
metadata:
  name: serilog-enrichers-kubernetes
spec:
  containers:
    - name: client-container
      image: k8s.gcr.io/busybox:1.24
      command: ["sh", "-c"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: POD_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: limits.cpu
              divisor: 1m
        - name: POD_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: requests.cpu
              divisor: 1m
        - name: POD_EPHEMERAL_STORAGE_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: requests.ephemeral-storage
              divisor: 1Gi
        - name: POD_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: limits.memory
              divisor: 1Mi
        - name: POD_MEMORY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: requests.memory
              divisor: 1Mi
        - name: POD_EPHEMERAL_STORAGE_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: limits.ephemeral-storage
              divisor: 1Gi
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POS_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name