apiVersion: v1
kind: Pod
metadata:
  name: serilog-enrichers-kubernetes
spec:
  containers:
    - name: client-container
      image: k8s.gcr.io/busybox:1.24
      command: ["sh", "-c"]
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "cpu_limit"
            resourceFieldRef:
              containerName: client-container
              resource: limits.cpu
              divisor: 1m
          - path: "cpu_request"
            resourceFieldRef:
              containerName: client-container
              resource: requests.cpu
              divisor: 1m
          - path: "ephemeral_storage_request"
            resourceFieldRef:
              containerName: client-container
              resource: requests.ephemeral-storage
              divisor: 1Gi
          - path: "mem_limit"
            resourceFieldRef:
              containerName: client-container
              resource: limits.memory
              divisor: 1Mi
          - path: "mem_request"
            resourceFieldRef:
              containerName: client-container
              resource: requests.memory
              divisor: 1Mi
          - path: "ephemeral_storage_limit"
            resourceFieldRef:
              containerName: client-container
              resource: limits.ephemeral-storage
              divisor: 1Gi
          - path: "node_name"
            fieldRef:
              fieldPath: spec.nodeName
          - path: "host_ip"
            fieldRef:
              fieldPath: status.hostIP
          - path: "pod_ip"
            fieldRef:
              fieldPath: status.podIP
          - path: "service_account_name"
            fieldRef:
              fieldPath: spec.serviceAccountName
          - path: "uid"
            fieldRef:
              fieldPath: metadata.uid
          - path: "namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "name"
            fieldRef:
              fieldPath: metadata.name
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations